/**
 * Email domains that belong to a consumer mailbox provider rather than to one organization.
 *
 * This is the difference between "everyone at this domain is a colleague" and "everyone at this
 * domain is a stranger". An organization is keyed on `organization.domain`, so treating a provider
 * domain as a company pools unrelated people into one organization, as its owners, able to see each
 * other's applications - and, since the Members page shows contact details, each other's names and
 * email addresses.
 *
 * That is not hypothetical: this list held only `gmail.com` for months, and an `Outlook` organization
 * accumulated three unrelated people that way.
 *
 * ## This list is a floor, not the mechanism
 *
 * It cannot be made complete, and not only because there are tens of thousands of providers. Two
 * cases are impossible for *any* denylist to catch:
 *
 * - **A personal domain that looks corporate.** Proton, Fastmail and iCloud+ all let an individual
 *   attach their own domain, so `tom@piaggio.dev` is one person's mailbox that no list can recognise.
 * - **A shared domain that is not a mailbox provider.** A university pools thousands of unrelated
 *   people behind `@stanford.edu`; so does an ISP, a coworking space, or a country's civil service.
 *
 * The failure is also asymmetric, which is what makes the guess dangerous rather than merely wrong:
 * missing a provider **pools strangers** into one organization and exposes their details, while
 * wrongly listing a company only **splits colleagues**, who can invite each other. A mechanism that
 * has to guess should therefore lean towards "separate", and this one leans the other way - it
 * auto-joins unless it recognises the domain.
 *
 * The two ways out, neither of which is a longer list:
 *
 * 1. **Don't auto-join an unverified domain at all.** Give every signup its own organization and make
 *    domain capture something an organization opts into after proving control of the domain (a DNS
 *    record), which is what Slack, Notion, Linear and Vercel do. Then this list stops being a safety
 *    control.
 * 2. **Ask the identity provider instead of guessing.** Google sends the `hd` claim only for a
 *    Workspace-managed domain, and Microsoft's `tid` is the consumer tenant
 *    `9188040d-6c67-4c5b-b112-36a304b66dad` for a personal account. Those are positive assertions of
 *    exactly the fact we are trying to infer. `auth.ts` already decodes `hd`; it just isn't threaded
 *    to where the organization is chosen.
 *
 * Until then: entries here are the well-known providers, and anything not listed is treated as a
 * company domain.
 */
const CONSUMER_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
    // ---- Google ----
    "gmail.com",
    "googlemail.com",

    // ---- Microsoft ----
    // The consumer tiers of the provider Entra also serves, so the easiest family to mistake for
    // corporate. Microsoft shipped country-specific domains for each generation of the product, and
    // they all still receive mail.
    "outlook.com",
    "outlook.at",
    "outlook.be",
    "outlook.cl",
    "outlook.co.id",
    "outlook.co.il",
    "outlook.co.nz",
    "outlook.co.th",
    "outlook.com.ar",
    "outlook.com.au",
    "outlook.com.br",
    "outlook.com.gr",
    "outlook.com.pe",
    "outlook.com.tr",
    "outlook.com.vn",
    "outlook.cz",
    "outlook.de",
    "outlook.dk",
    "outlook.es",
    "outlook.fr",
    "outlook.hu",
    "outlook.ie",
    "outlook.in",
    "outlook.it",
    "outlook.jp",
    "outlook.kr",
    "outlook.lv",
    "outlook.my",
    "outlook.nl",
    "outlook.ph",
    "outlook.pt",
    "outlook.sa",
    "outlook.sg",
    "outlook.sk",
    "hotmail.com",
    "hotmail.be",
    "hotmail.ca",
    "hotmail.ch",
    "hotmail.cl",
    "hotmail.co.id",
    "hotmail.co.il",
    "hotmail.co.in",
    "hotmail.co.jp",
    "hotmail.co.nz",
    "hotmail.co.th",
    "hotmail.co.uk",
    "hotmail.co.za",
    "hotmail.com.ar",
    "hotmail.com.au",
    "hotmail.com.br",
    "hotmail.com.hk",
    "hotmail.com.mx",
    "hotmail.com.pe",
    "hotmail.com.tr",
    "hotmail.com.tw",
    "hotmail.com.vn",
    "hotmail.cz",
    "hotmail.de",
    "hotmail.dk",
    "hotmail.es",
    "hotmail.fi",
    "hotmail.fr",
    "hotmail.gr",
    "hotmail.hu",
    "hotmail.ie",
    "hotmail.it",
    "hotmail.kz",
    "hotmail.lv",
    "hotmail.my",
    "hotmail.nl",
    "hotmail.no",
    "hotmail.ph",
    "hotmail.rs",
    "hotmail.se",
    "hotmail.sg",
    "hotmail.sk",
    "live.com",
    "live.at",
    "live.be",
    "live.ca",
    "live.cl",
    "live.cn",
    "live.co.kr",
    "live.co.uk",
    "live.co.za",
    "live.com.ar",
    "live.com.au",
    "live.com.mx",
    "live.com.my",
    "live.com.pt",
    "live.com.sg",
    "live.de",
    "live.dk",
    "live.fi",
    "live.fr",
    "live.hk",
    "live.ie",
    "live.in",
    "live.it",
    "live.jp",
    "live.nl",
    "live.no",
    "live.ph",
    "live.ru",
    "live.se",
    "msn.com",
    "passport.com",
    "windowslive.com",

    // ---- Apple ----
    "icloud.com",
    "me.com",
    "mac.com",

    // ---- Yahoo / AOL ----
    "yahoo.com",
    "yahoo.ca",
    "yahoo.cn",
    "yahoo.co.id",
    "yahoo.co.il",
    "yahoo.co.in",
    "yahoo.co.jp",
    "yahoo.co.kr",
    "yahoo.co.nz",
    "yahoo.co.th",
    "yahoo.co.uk",
    "yahoo.co.za",
    "yahoo.com.ar",
    "yahoo.com.au",
    "yahoo.com.br",
    "yahoo.com.co",
    "yahoo.com.hk",
    "yahoo.com.mx",
    "yahoo.com.my",
    "yahoo.com.ph",
    "yahoo.com.sg",
    "yahoo.com.tr",
    "yahoo.com.tw",
    "yahoo.com.vn",
    "yahoo.cz",
    "yahoo.de",
    "yahoo.dk",
    "yahoo.es",
    "yahoo.fi",
    "yahoo.fr",
    "yahoo.gr",
    "yahoo.hu",
    "yahoo.ie",
    "yahoo.in",
    "yahoo.it",
    "yahoo.nl",
    "yahoo.no",
    "yahoo.pl",
    "yahoo.pt",
    "yahoo.ro",
    "yahoo.se",
    "ymail.com",
    "rocketmail.com",
    "aol.com",
    "aol.co.uk",
    "aol.de",
    "aol.fr",
    "aim.com",
    "verizon.net",
    "sbcglobal.net",
    "bellsouth.net",
    "att.net",
    "frontier.com",
    "frontiernet.net",

    // ---- Privacy-focused ----
    // Every one of these also sells custom-domain hosting to individuals, which is the case a list
    // structurally cannot catch - see the note above.
    "proton.me",
    "protonmail.com",
    "protonmail.ch",
    "pm.me",
    "tutanota.com",
    "tutanota.de",
    "tuta.com",
    "tuta.io",
    "keemail.me",
    "mailbox.org",
    "posteo.de",
    "posteo.net",
    "startmail.com",
    "hushmail.com",
    "runbox.com",
    "disroot.org",
    "riseup.net",
    "systemli.org",
    "autistici.org",
    "cock.li",

    // ---- Other large free providers ----
    "gmx.com",
    "gmx.at",
    "gmx.ch",
    "gmx.de",
    "gmx.es",
    "gmx.fr",
    "gmx.li",
    "gmx.net",
    "gmx.us",
    "web.de",
    "mail.com",
    "email.com",
    "usa.com",
    "consultant.com",
    "europe.com",
    "post.com",
    "writeme.com",
    "zoho.com",
    "zohomail.com",
    "fastmail.com",
    "fastmail.fm",
    "fastmail.us",
    "hey.com",
    "hushmail.me",
    "inbox.com",
    "lycos.com",
    "mail.ru",
    "inbox.ru",
    "bk.ru",
    "list.ru",
    "internet.ru",
    "yandex.com",
    "yandex.ru",
    "yandex.by",
    "yandex.kz",
    "yandex.ua",
    "ya.ru",
    "rambler.ru",
    "zoznam.sk",
    "seznam.cz",
    "centrum.cz",
    "centrum.sk",
    "onet.pl",
    "op.pl",
    "wp.pl",
    "interia.pl",
    "o2.pl",
    "gazeta.pl",
    "poczta.onet.pl",
    "abv.bg",
    "mail.bg",
    "freemail.hu",
    "citromail.hu",
    "indamail.hu",
    "libero.it",
    "virgilio.it",
    "alice.it",
    "tin.it",
    "tiscali.it",
    "inwind.it",
    "iol.it",
    "orange.fr",
    "wanadoo.fr",
    "free.fr",
    "laposte.net",
    "sfr.fr",
    "neuf.fr",
    "bbox.fr",
    "voila.fr",
    "club-internet.fr",
    "telenet.be",
    "skynet.be",
    "scarlet.be",
    "planet.nl",
    "ziggo.nl",
    "kpnmail.nl",
    "home.nl",
    "chello.nl",
    "xs4all.nl",
    "telia.com",
    "telia.se",
    "spray.se",
    "bredband.net",
    "online.no",
    "start.no",
    "broadpark.no",
    "sol.dk",
    "mail.dk",
    "post.dk",
    "tdcspace.dk",
    "luukku.com",
    "suomi24.fi",
    "elisanet.fi",
    "kolumbus.fi",
    "bluewin.ch",
    "sunrise.ch",
    "t-online.de",
    "freenet.de",
    "arcor.de",
    "1und1.de",
    "unitybox.de",
    "vodafone.de",
    "aon.at",
    "chello.at",
    "a1.net",
    "terra.es",
    "telefonica.net",
    "ya.com",
    "wanadoo.es",
    "sapo.pt",
    "netcabo.pt",
    "iol.pt",
    "btinternet.com",
    "sky.com",
    "talktalk.net",
    "virginmedia.com",
    "blueyonder.co.uk",
    "ntlworld.com",
    "tiscali.co.uk",
    "eircom.net",
    "shaw.ca",
    "rogers.com",
    "sympatico.ca",
    "telus.net",
    "videotron.ca",
    "cogeco.ca",
    "comcast.net",
    "cox.net",
    "charter.net",
    "earthlink.net",
    "juno.com",
    "netzero.net",
    "optonline.net",
    "roadrunner.com",
    "rr.com",
    "twc.com",
    "windstream.net",
    "centurylink.net",
    "q.com",
    "pacbell.net",
    "prodigy.net",
    "prodigy.net.mx",
    "bigpond.com",
    "bigpond.net.au",
    "optusnet.com.au",
    "iinet.net.au",
    "tpg.com.au",
    "internode.on.net",
    "xtra.co.nz",

    // ---- Latin America ----
    "uol.com.br",
    "bol.com.br",
    "terra.com.br",
    "terra.com",
    "terra.com.mx",
    "terra.com.ar",
    "globo.com",
    "globomail.com",
    "ig.com.br",
    "r7.com",
    "zipmail.com.br",
    "itelefonica.com.br",
    "oi.com.br",
    "veloxmail.com.br",

    // ---- Asia ----
    "qq.com",
    "vip.qq.com",
    "foxmail.com",
    "163.com",
    "126.com",
    "yeah.net",
    "sina.com",
    "sina.cn",
    "sohu.com",
    "aliyun.com",
    "tom.com",
    "21cn.com",
    "naver.com",
    "hanmail.net",
    "daum.net",
    "nate.com",
    "kakao.com",
    "docomo.ne.jp",
    "ezweb.ne.jp",
    "softbank.ne.jp",
    "i.softbank.jp",
    "nifty.com",
    "biglobe.ne.jp",
    "ocn.ne.jp",
    "so-net.ne.jp",
    "excite.co.jp",
    "goo.jp",
    "rediffmail.com",
    "rediff.com",
    "sify.com",
    "indiatimes.com",
    "in.com",
    "bsnl.in",
    "vsnl.net",
    "vsnl.com",

    // ---- Middle East & Africa ----
    "maktoob.com",
    "walla.com",
    "walla.co.il",
    "nana10.co.il",
    "netvision.net.il",
    "bezeqint.net",
    "webmail.co.za",
    "mweb.co.za",
    "telkomsa.net",
    "vodamail.co.za",
    "yandex.com.tr",
    "mynet.com",
    "superonline.com",
    "ttmail.com",
]);

/**
 * Whether this email domain is a consumer mailbox provider, meaning two accounts sharing it are
 * strangers rather than colleagues.
 *
 * Exported as a predicate rather than the set so no caller can iterate it, mutate it, or re-derive a
 * partial copy - the membership question is the only thing anyone needs to ask. Case and surrounding
 * whitespace are normalized here, because the domains arrive from an identity provider unnormalised.
 */
export function isConsumerEmailDomain(domain: string): boolean {
    return CONSUMER_EMAIL_DOMAINS.has(domain.trim().toLowerCase());
}
