import type { RouterOutputs } from "lib/trpc";
import { makeOrganization, makeSession } from "./auth-fixtures";
import { authHandlers } from "./auth-handlers";
import type { TrpcFixtures } from "./trpc-handler";
import { trpcHandler } from "./trpc-handler";

const FIXTURE_EPOCH = new Date("2026-01-01T00:00:00.000Z");
const ORG_ID = "org_fixture_01";

/**
 * One realistic WEB application, shaped exactly like `applications.list`
 * returns it. Stories can reference its slug ("acme-web") in page paths.
 */
export const baseApplication: RouterOutputs["applications"]["list"][number] = {
    id: "app_fixture_01",
    name: "Acme Web",
    slug: "acme-web",
    architecture: "WEB",
    customInstructions: null,
    testScopeGuidelines: null,
    disabled: false,
    githubRepositoryId: 123456,
    mainBranchId: "branch_fixture_01",
    signingSecretEnc: null,
    createdAt: FIXTURE_EPOCH,
    updatedAt: FIXTURE_EPOCH,
    organizationId: ORG_ID,
    mainBranch: {
        name: "main",
        deployment: {
            id: "deployment_fixture_01",
            active: true,
            branchId: "branch_fixture_01",
            webhookUrl: null,
            webhookHeaders: null,
            createdAt: FIXTURE_EPOCH,
            updatedAt: FIXTURE_EPOCH,
            organizationId: ORG_ID,
            webDeployment: {
                deploymentId: "deployment_fixture_01",
                url: "https://app.acme.example.com",
                file: null,
                createdAt: FIXTURE_EPOCH,
                updatedAt: FIXTURE_EPOCH,
                organizationId: ORG_ID,
            },
            mobileDeployment: null,
        },
    },
    onboardingState: { step: "completed" },
};

/**
 * The sidebar's suite-health meter renders on every page under the app shell, so the baseline must answer it.
 * CALIBRATING is the default every real app starts at, which makes it the honest baseline here too.
 */
export const baseSuiteHealth: RouterOutputs["applications"]["suiteHealth"] = {
    level: "calibrating",
    rank: 3,
    score: 54,
    trust: 46,
    evidence: {
        runs: 21,
        pullRequests: 3,
        selfHeals: 2,
        selfHealAttempts: 6,
        findings: 63,
        ageDays: 11,
        daysSinceLastRun: 0,
    },
    breakdown: {
        passed: 29,
        clientBug: 0,
        environmentFailure: 6,
        scenarioIssue: 8,
        planMismatch: 11,
        engineArtifact: 9,
        invalidTest: 0,
    },
    driver: "balanced",
    staleIssues: 0,
    gatedBy: undefined,
    hasEverRun: true,
};

/**
 * The "fix it" backlog: how much is unresolved, and the prompt that hands it over. Numbers and prompt shape taken
 * from `centinel-finance/centinel-app`.
 */
export const baseSuiteHealthFixPlan: RouterOutputs["applications"]["suiteHealthFixPlan"] = {
    repoFullName: "acme/acme-web",
    totalIssues: 17,
    byKind: { bug: 2, environment: 8, scenario: 7 },
    oldestAgeDays: 6,
    truncated: false,
    clusters: [
        {
            title: "Scenario setup failed before the app was exercised: SDK returned HTTP 500",
            kind: "scenario",
            branches: 4,
            openBranches: 2,
            findings: 11,
        },
    ],
    // Generated by running `suiteHealthFixPrompt` over the counts above - never hand-edited. The prompt
    // is what the copy button puts on the clipboard, so a drifted fixture is a story that lies about the
    // product.
    prompt: [
        "Use the `autonoma` MCP to work",
        "through this. Its tools are how you read each failure and fix it.",
        "",
        "Autonoma reports SUITE HEALTH: DEGRADED (1/5) for acme/acme-web.",
        "17 findings are unresolved (8 environment, 7 scenario, 2 bug).",
        "",
        "START HERE - open pull requests, blocked right now (most findings first):",
        "  · #2130 Per-supplier invoice extraction config + total-only line items - 4 findings (2 scenario, 1 bug, 1 environment), 6d",
        "  · #2054 Bump the all-dependencies group across 1 directory with 28 updates - 7 findings (5 environment, 2 scenario), 4d",
        "",
        "Most of this is probably ONE problem. These findings repeat across pull requests:",
        '  · 4 pull requests, 2 still open - 11 findings - "Scenario setup failed before the app was exercised: SDK returned HTTP 500"',
        "",
        "Diagnose the shared cause FIRST and fix it once, then re-run and see how many clear before you",
        "move on. Do not work these one at a time - one fix often clears most of the backlog.",
        "",
        "Already merged or closed - do NOT go fix these. They are here only because their runs may",
        "show the same failure with more evidence:",
        "  · main (main branch) - 2 findings (1 bug, 1 environment), 6d",
        "  · #2125 Let workspace admins edit invoices after publishing - 4 findings (3 scenario, 1 environment), 5d",
        "",
        "For each finding, call get_analysis(repoFullName, prNumber) and read it. The finding's `kind`",
        "tells you where its fix lives:",
        "",
        "  · environment -> the preview could not run properly - a missing secret, a broken service. Fix it with get_secret_status / set_secret / edit_previewkit_config. No repo change needed.",
        "  · scenario    -> the test data was missing or wrong. Fix it with list_scenarios / get_recipe / update_recipe / dry_run_scenario. Takes effect with no redeploy.",
        "  · bug         -> the app misbehaved. Fix it in this repo and push to the pull request's branch.",
        "",
        "Do NOT disable, skip or delete a test to make a run go green - if a test is genuinely wrong about",
        "the app, say so and explain why rather than removing it quietly. Report what you changed, and",
        "which pull requests each change should clear.",
    ].join("\n"),
};

/**
 * A fully onboarded application. The app shell's sidebar reads this on every page to decide whether to nudge the
 * user to finish setup, so a story about anything else says "completed" and gets the nudge out of the frame.
 */
export function completedOnboardingState(): RouterOutputs["onboarding"]["getState"] {
    return {
        id: "onboarding_fixture_01",
        applicationId: baseApplication.id,
        step: "completed",
        agentConnectedAt: null,
        agentLogs: [],
        productionUrl: "https://app.acme.example.com",
        previewEnvironmentMode: "previewkit",
        previewUrl: null,
        previewVerificationStatus: "ready",
        previewDeployRequestedAt: null,
        completedAt: FIXTURE_EPOCH,
        lastDiscoveryError: null,
        lastDiscoveredAt: FIXTURE_EPOCH,
        lastDiscoveredModels: 12,
        discoveringStartedAt: null,
        dryRunPassedAt: FIXTURE_EPOCH,
        diffTriggerConfirmedAt: FIXTURE_EPOCH,
        agentHolder: "human",
        agentLastActivityAt: null,
        agentPendingRequest: null,
        agentPairingCode: null,
        agentPairingExpiresAt: null,
        agentClient: null,
        createdAt: FIXTURE_EPOCH,
        updatedAt: FIXTURE_EPOCH,
        sdkConfigured: true,
        dryRunPassed: true,
        discoveryInProgress: false,
        artifactsUploaded: true,
        hasContent: true,
        setupComplete: true,
    };
}

const baseTrpcFixtures: TrpcFixtures = {
    auth: {
        orgStatus: "approved",
        // The app shell (route.tsx / useActiveOrg) resolves the active org on
        // every page under it, so the baseline must answer it or those stories
        // render an error.
        activeOrg: {
            id: ORG_ID,
            name: "Acme",
            slug: "acme",
            isDemo: false,
            canReturnToAccount: false,
            mergeGateEnabled: true,
            vercelMarketplaceEntry: false,
            needsNaming: false,
        },
    },
    applications: {
        list: [baseApplication],
        suiteHealth: baseSuiteHealth,
        suiteHealthFixPlan: baseSuiteHealthFixPlan,
    },
    // Every "what is unresolved on main" surface reads this one query, so the baseline answers it with a quiet
    // application - a story that does not care about main's problems renders the empty state instead of erroring.
    branches: { mainOpenProblems: [] },
    github: { getInstallation: null },
    // List views poll preview liveness; default to none so a story that doesn't
    // set it renders without the badge (and never errors on the unmocked call).
    previewAccess: { livenessForApplication: {}, livenessForFleet: {} },
    billing: {
        status: {
            creditBalance: 740,
            subscriptionCreditBalance: 500,
            topupCreditBalance: 240,
            provider: "stripe",
            subscriptionStatus: "active",
            currentPeriodEnd: new Date("2026-02-01T00:00:00.000Z"),
            cancelAtPeriodEnd: false,
            gracePeriodEndsAt: undefined,
            autoTopUpEnabled: false,
            autoTopUpThreshold: 0,
            cliCreditsSpent: 60,
            transactions: [],
        },
    },
};

/**
 * MSW handlers that satisfy the app-shell guards (session, active org,
 * approved org status, one application) so any page under the shell renders.
 * Page-specific tRPC fixtures deep-merge over the baseline.
 *
 * Pass `role: "admin"` for the pages behind the admin guard - they redirect to
 * "/" for anyone else, so a story without it screenshots the home page.
 */
type BranchPage = RouterOutputs["branches"]["list"];

/**
 * A `branches.list` page around some rows. The envelope (totals, page size) is the server's, so stories build it
 * here rather than each spelling out a shape that would then drift one story at a time.
 */
export function branchPage(items: BranchPage["items"] = [], page = 1): BranchPage {
    return { items, totalCount: items.length, page, pageSize: 25 };
}

export function appShellHandlers(pageFixtures: TrpcFixtures = {}, { role }: { role?: string } = {}) {
    return [
        trpcHandler(mergeTrpcFixtures(baseTrpcFixtures, pageFixtures)),
        ...authHandlers({ session: makeSession({ role }), organizations: [makeOrganization()] }),
    ];
}

function mergeTrpcFixtures(base: TrpcFixtures, extra: TrpcFixtures): TrpcFixtures {
    const merged: TrpcFixtures = { ...base };
    for (const key of Object.keys(extra)) {
        const router = key satisfies string;
        Object.assign(merged, { [router]: { ...Reflect.get(base, router), ...Reflect.get(extra, router) } });
    }
    return merged;
}
