import { readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { glob } from "glob";
import { debugLog } from "../../core/debug";
import { INVALID_DIR, isTestFile, TEST_FILE_GLOB, TEST_INDEX_FILE, TESTS_DIR } from "../../core/test-files";
import type { CoverageState } from "./graph";

const STEP_VERBS = /^\d+\.\s+(click|type|scroll|assert|hover|drag|read|refresh):/gm;
const INTERACTION_VERBS = /^\d+\.\s+(click|type|drag):/gm;

interface TestStats {
    criticality: string;
    steps: number;
    interactions: number;
}

/** What the index summarizes about one test. Unreadable files count as empty. */
async function scanTest(outputDir: string, path: string): Promise<TestStats> {
    try {
        const content = await readFile(join(outputDir, path), "utf-8");
        return {
            criticality: content.match(/criticality:\s*(\w+)/)?.[1] ?? "",
            steps: content.match(STEP_VERBS)?.length ?? 0,
            interactions: content.match(INTERACTION_VERBS)?.length ?? 0,
        };
    } catch (err) {
        debugLog("Skipping a test file the index could not read", { path, err });
        return { criticality: "", steps: 0, interactions: 0 };
    }
}

/**
 * The suite as it exists on disk, relative to the output dir. Read back rather
 * than taken from the generator's own tally: by the time the index is written
 * the suite has also gained journey tests, lost tests the review cycle deleted,
 * and had invalid ones quarantined - none of which the tally knows about.
 */
async function listSuiteTests(outputDir: string): Promise<string[]> {
    const absolute = await glob(join(outputDir, TESTS_DIR, TEST_FILE_GLOB));
    return absolute
        .filter((path) => isTestFile(path) && !path.includes(`/${INVALID_DIR}/`))
        .map((path) => relative(outputDir, path))
        .sort();
}

export async function generateIndex(outputDir: string, state: CoverageState): Promise<void> {
    const testPaths = await listSuiteTests(outputDir);
    const testsByFolder = new Map<string, string[]>();

    for (const p of testPaths) {
        const parts = p.split("/");
        if (parts.length >= 3) {
            const folder = parts[1]!;
            const existing = testsByFolder.get(folder) ?? [];
            existing.push(p);
            testsByFolder.set(folder, existing);
        }
    }

    const stats = state.summary();
    const folders = [...testsByFolder.entries()].map(([name, tests]) => ({
        name,
        test_count: tests.length,
    }));

    const critCounts = new Map([
        ["critical", 0],
        ["high", 0],
        ["mid", 0],
        ["low", 0],
    ]);
    let totalSteps = 0;
    let totalInteractions = 0;

    // One read per test, all at once: a suite is hundreds of small files and
    // nothing here depends on another file's contents, so reading them in
    // sequence spent the whole index write waiting on the disk.
    const scanned = await Promise.all(testPaths.map((path) => scanTest(outputDir, path)));
    for (const stats of scanned) {
        if (critCounts.has(stats.criticality)) {
            critCounts.set(stats.criticality, (critCounts.get(stats.criticality) ?? 0) + 1);
        }
        totalSteps += stats.steps;
        totalInteractions += stats.interactions;
    }

    const totalTests = testPaths.length;
    const avgSteps = totalTests > 0 ? (totalSteps / totalTests).toFixed(1) : "0";

    let content = `---
total_tests: ${totalTests}
total_folders: ${folders.length}
avg_steps_per_test: ${avgSteps}
total_interactions: ${totalInteractions}
criticality:
  critical: ${critCounts.get("critical") ?? 0}
  high: ${critCounts.get("high") ?? 0}
  mid: ${critCounts.get("mid") ?? 0}
  low: ${critCounts.get("low") ?? 0}
folders:
${folders.map((f) => `  - name: "${f.name}"\n    test_count: ${f.test_count}`).join("\n")}
---

# Test Suite Index

Generated by BFS exploration. ${stats.tested} nodes tested, ${stats.skipped} skipped.

## Folders

| Folder | Tests |
|--------|-------|
${folders.map((f) => `| ${f.name} | ${f.test_count} |`).join("\n")}

## All Tests

${[...testsByFolder.entries()].flatMap(([_folder, tests]) => tests.map((t) => `- \`${t}\``)).join("\n")}
`;

    await writeFile(join(outputDir, TESTS_DIR, TEST_INDEX_FILE), content, "utf-8");
}
