import { describe, expect, it } from "vitest";
import { categorizeInfraFailure } from "../src/rules/infra-failure";

describe("categorizeInfraFailure", () => {
    it("maps SDK 5xx / seeding failures to scenario_issue", () => {
        for (const message of [
            "SDK returned HTTP 500: Failed query: select ...",
            "SDK returned HTTP 502: bad gateway",
            "SDK returned HTTP 500: canceling statement due to statement timeout",
            "SDK returned HTTP 500: auth sign-in failed for admin",
        ]) {
            expect(categorizeInfraFailure(message)).toBe("scenario_issue");
        }
    });

    it("maps an SDK-contextual missing/unreachable endpoint, or a raw transport error, to environment_failure", () => {
        for (const message of [
            "SDK returned HTTP 404: <html>",
            "SDK returned HTTP 503: unavailable",
            "SDK returned HTTP 504: gateway timeout",
            "SDK call timed out after 90s - ensure your endpoint is reachable",
            // Transport-level errors are unambiguous regardless of who raised them.
            "connect ECONNREFUSED 10.0.0.1:443",
            "getaddrinfo ENOTFOUND preview.example.test",
            "socket hang up",
        ]) {
            expect(categorizeInfraFailure(message)).toBe("environment_failure");
        }
    });

    it("does NOT categorize a bare timeout / fetch failure with no SDK context (could be the model API mid-classify)", () => {
        // The reviewer's case: a classifier/model-API failure whose message happens to contain network-ish words
        // must stay classification_error, not be mislabeled as "the preview was unavailable".
        for (const message of [
            "fetch failed",
            "The operation timed out",
            "Activity task timed out",
            "request to https://api.openai.com timed out",
        ]) {
            expect(categorizeInfraFailure(message)).toBeUndefined();
        }
    });

    it("returns undefined for a message that is NOT a recognizable infra failure (a real classifier bug)", () => {
        // These must NOT be buried as provisioning failures - they should stay classification_error so the bug shows.
        for (const message of [
            "Cannot read properties of undefined (reading 'plan')",
            "No output generated by the model",
            "Unexpected verdict shape",
        ]) {
            expect(categorizeInfraFailure(message)).toBeUndefined();
        }
    });
});
