import { describe, expect, it } from "vitest";
import { categorizeInfraFailure, infraFailureResult, scenarioSetupFailureResult } from "../src/scenario-setup-failure";

describe("scenarioSetupFailureResult", () => {
    it("produces a real verdict (never a missing-verdict / classification_error result)", () => {
        const result = scenarioSetupFailureResult({ slug: "some-test", message: "boom" });
        expect(result.verdict).toBeDefined();
        expect(result.verdict?.ran).toBe(false);
        expect(result.verdict?.isClientBug).toBe(false);
        expect(result.runSuccess).toBe(false);
        // The error text is carried as evidence so the cause is visible in the report.
        expect(result.verdict?.evidence[0]?.detail).toBe("boom");
    });

    it("categorizes a missing/unreachable preview as environment_failure", () => {
        const cases = [
            `SDK returned HTTP 404: Error parsing response: Unexpected token '<', "<html>`,
            "SDK returned HTTP 503: Error parsing response",
            "SDK call timed out after 90s - ensure your endpoint is reachable and responds quickly",
            "fetch failed",
            "Activity task timed out",
        ];
        for (const message of cases) {
            expect(scenarioSetupFailureResult({ slug: "t", message }).verdict?.category).toBe("environment_failure");
        }
    });

    it("categorizes a seeding (5xx) failure as scenario_issue", () => {
        const cases = [
            'SDK returned HTTP 500: Failed query: select "id" from "user_profiles" where "stytch_member_id" = $1',
            "SDK returned HTTP 500: canceling statement due to statement timeout",
            "SDK returned HTTP 500: auth sign-in failed for demo-admin+abc@autonoma.test",
        ];
        for (const message of cases) {
            expect(scenarioSetupFailureResult({ slug: "t", message }).verdict?.category).toBe("scenario_issue");
        }
    });

    it("defaults an unrecognized failure to environment_failure (conservative, not the PR's fault)", () => {
        expect(scenarioSetupFailureResult({ slug: "t", message: "something odd happened" }).verdict?.category).toBe(
            "environment_failure",
        );
    });
});

describe("categorizeInfraFailure", () => {
    it("maps SDK 5xx / seeding failures to scenario_issue", () => {
        for (const message of [
            "SDK returned HTTP 500: Failed query: select ...",
            "SDK returned HTTP 502: bad gateway",
            "SDK returned HTTP 500: canceling statement due to statement timeout",
            "SDK returned HTTP 500: auth sign-in failed for admin",
        ]) {
            expect(categorizeInfraFailure(message)).toBe("scenario_issue");
        }
    });

    it("maps an SDK-contextual missing/unreachable endpoint, or a raw transport error, to environment_failure", () => {
        for (const message of [
            "SDK returned HTTP 404: <html>",
            "SDK returned HTTP 503: unavailable",
            "SDK returned HTTP 504: gateway timeout",
            "SDK call timed out after 90s - ensure your endpoint is reachable",
            // Transport-level errors are unambiguous regardless of who raised them.
            "connect ECONNREFUSED 10.0.0.1:443",
            "getaddrinfo ENOTFOUND preview.example.test",
            "socket hang up",
        ]) {
            expect(categorizeInfraFailure(message)).toBe("environment_failure");
        }
    });

    it("does NOT categorize a bare timeout / fetch failure with no SDK context (could be the model API mid-classify)", () => {
        // The reviewer's case: a classifier/model-API failure whose message happens to contain network-ish words
        // must stay classification_error, not be mislabeled as "the preview was unavailable".
        for (const message of [
            "fetch failed",
            "The operation timed out",
            "Activity task timed out",
            "request to https://api.openai.com timed out",
        ]) {
            expect(categorizeInfraFailure(message)).toBeUndefined();
        }
    });

    it("returns undefined for a message that is NOT a recognizable infra failure (a real classifier bug)", () => {
        // These must NOT be buried as provisioning failures - they should stay classification_error so the bug shows.
        for (const message of [
            "Cannot read properties of undefined (reading 'plan')",
            "No output generated by the model",
            "Unexpected verdict shape",
        ]) {
            expect(categorizeInfraFailure(message)).toBeUndefined();
        }
    });
});

describe("infraFailureResult", () => {
    it("builds a categorized provisioning verdict for a recognizable SDK error", () => {
        const result = infraFailureResult({ slug: "t", message: "SDK returned HTTP 500: Failed query" });
        expect(result?.verdict?.category).toBe("scenario_issue");
        expect(result?.verdict?.ran).toBe(false);
        expect(result?.verdict?.isClientBug).toBe(false);
        expect(result?.verdict?.evidence[0]?.detail).toContain("HTTP 500");
    });

    it("returns undefined for a non-infra error, so the caller keeps the honest classification_error", () => {
        expect(infraFailureResult({ slug: "t", message: "Cannot read properties of undefined" })).toBeUndefined();
    });
});
